@token = ;
###

GET http://localhost:8080/api/games HTTP/1.1


###

GET http://localhost:8080/api/highscores HTTP/1.1

###

PUT http://localhost:8080/api/highscores/100 HTTP/1.1
Content-Type: application/json

{
    "userId": 100,
    "highScore": 1,
    "disabled": false,
    "userName": "production",
    "highScoreId": 100
}

###
POST http://localhost:8080/api/adduser HTTP/1.1
Content-Type: application/json

{
    "username": "matthewdelmarsteckelberge",
    "password": "P@ssw0rd!",
    "roles": ["USER"]
}

###

POST http://localhost:8080/api/security/authenticate
Content-Type: application/json

{
    "username": "matthew",
    "password": "P@ssw0rd!"
}
###


GET http://localhost:8080/api/users HTTP/1.1


###

PUT http://localhost:8080/api/users/enabled/23 HTTP/1.1
Content-Type: application/json

{
    "appUserId": 23,
    "username": "know",
    "password": "$2a$10$ntB7CsRKQzuLoKY3rfoAQen5nNyiC/U60wBsWnnYrtQQi8Z3IZzQa",
    "disabled": true,
    "roles": ["USER"]
}

###

GET http://localhost:8080/api/highscores HTTP/1.1

###
